# Generated by Django 2.0 on 2019-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_class', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=10)),
                ('product_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFetch',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('upload_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
